# These are supported funding model platforms

github: ['Dvnz99'] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
custom: ['https://wa.me/qr/3BE3DUEDYQWFO1','https://link.dana.id/qr/3wru4hg9'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
